# codExa - Numpy 入門

このコースがカバーしている内容

- Numpy配列の基本的な作り方
- Numpy配列の要素のアクセスの仕方
- Numpy配列生成の便利な関数の使い方
- Numpy配列と基本的な演算子
- Numpy配列とPython Listの簡単な比較
- 行列の基本的な演算（ドット積、アダマール積）
- 行列の処理（逆行列、転置行列、対角成分の取得、内積/外積）
- 数学系の関数（三角関数、指数/対数関数、小数の扱い）

## 3. Numpyとは？

チャプター3では、Numpyの基本的な概要をみていきましょう。実際にiPythonを立ち上げて、Numpyのインポートとバージョン確認を行います。

- Numpyは数値計算を効率的に行うためのPython拡張ライブラリ
- 多次元配列の操作/演算を行うのに便利
- 機械学習では必須のライブラリです
- 全ての操作を覚える必要はありません
- 基本的な操作のみ覚えて必要に応じて公式ドキュメントを利用

In [1]:
import numpy as np
print(np.__version__)

1.15.1


## 4. Numpy配列

チャプター4「Numpy 配列」では、Numpy配列の生成や、データのアクセスの方法を学びましょう。またNumpy配列生成で覚えておくと便利な関数も紹介しています。

- Numpy配列の生成はnp.array()
- typeはnumpy.ndarray
- shapeで配列のサイズを確認
- array[0]で0行目の要素のアクセス
- array[2,3」で2行目3列目の要素のアクセス
- array[:2]で2行までアクセス
- array[2:]で行2からアクセス
- array[:2, 1]行2までの列1へアクセス
- np.zeros() 要素が全て0のNumpy配列の生成
- np.ones() 要素が全て1のNumpy配列の生成
- np.full() 指定した値を持つNumpy配列の生成
- np.eye() 単位行列のNumpy配列を生成

In [12]:
# 配列の作成
a = np.array([1,2,3])
a

array([1, 2, 3])

In [13]:
# タイプの確認
type(a)

numpy.ndarray

ndarray　= N Dimension(次元)　Array(配列)　…　N次元の配列

In [10]:
# 配列のサイズの確認
a.shape

(3,)

In [9]:
# 要素のデータ型の確認/指定
a.dtype

dtype('int64')

In [15]:
# 配列aの0番目の要素へアクセス
a[0]

1

In [16]:
a[1]

2

In [17]:
a[2]

3

In [19]:
# 新しい配列bの作成
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b.shape

(2, 3)

In [21]:
b.dtype

dtype('int64')

In [27]:
# 配列bの0行目の要素
b[0]

array([1, 2, 3])

In [28]:
# 配列bの1行目の要素
b[1]

array([4, 5, 6])

In [29]:
# 配列bの0行目0列目の要素
b[0][0]

1

In [30]:
# 配列bの0行目0列目の要素
b[0,0]

1

In [32]:
b[1,2]

6

In [33]:
# 新しい配列cの作成
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
c.shape

(3, 4)

In [35]:
# 配列cの２行目以前の要素（行範囲指定）
c[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
# 配列cの２行目以降の要素（行範囲指定）
c[2:]

array([[ 9, 10, 11, 12]])

In [38]:
# 配列cの２行1列の要素
c[:2, 1]

array([2, 6])

In [39]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
# 0を要素とする配列を生成
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
# 1を要素とする配列を生成
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [42]:
# 指定した値とサイズの配列を生成
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [44]:
# 単位行列を生成
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## 5. 基本的な演算

チャプター5「基本的な演算」では、Numpy配列と基本的な演算子「＋」や「-」を使って、どのような処理が行われるかを確認しましょう。またPythonのリストとNumpy配列の異なる点にも触れています。

- array + arrayは各要素の足し算
- array - arrayは各要素の引き算
- array * arrayは各要素の掛け算
- array ** 2は各要素の自乗
- array / 2は各要素の2の割り算
- array < 2は各要素が2より小さいかどうかのboolean
- PythonリストとNumpy配列の処理の違い

In [45]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# 足し算
a + b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [49]:
# 引き算
a - b

array([[0, 0, 0],
       [0, 0, 0]])

In [50]:
#  掛け算
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [51]:
# 各要素に対して自乗
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [52]:
#  割り算
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [53]:
# 各要素に対して２より小さいかBooleanで判別
a < 2

array([[ True, False, False],
       [False, False, False]])

In [54]:
# PythonリストとNumpy配列の処理の違い
array = np.array([1,2,3])
list = [1,2,3]

In [55]:
array

array([1, 2, 3])

In [56]:
list

[1, 2, 3]

In [57]:
# リストに値を追加
list + [4]

[1, 2, 3, 4]

In [58]:
# arrayに値を追加
array + [4]

array([5, 6, 7])

→　各要素毎に４が足し算される

In [59]:
# リストの各要素に追加する方法　→　for文を使う
list2 = []
for e  in list:
    list2.append(e + 4)
list2

[5, 6, 7]

Pythonのリストに対して、Numpy配列の方がfor文を使わずに簡単な構文で計算処理ができる。

In [60]:
# 要素毎の掛け算
list * 2

[1, 2, 3, 1, 2, 3]

Pythonのリストは、リストの同じ値が追加される

In [61]:
array * 2

array([2, 4, 6])

Numpy配列は、各要素に対して掛け算される

In [62]:
# リストの各要素に対して掛け算をする方法
list2 = []
for e in list:
    list2.append(e*2)
list2

[2, 4, 6]

## 6. 行列の積

チャプター6「行列の積」では、Numpyを使って行列（マトリックス）の積を求めましょう。またPythonリストからNumpy配列への変換も説明します。行列の積の求め方や線形代数の基礎に不安がある方は、線形代数 入門の講座も是非受講ください。

- 行列の積の計算方法
- ndarray * ndarray は各要素の掛け算
- np.dot()で行列の積を求められる
- a.dot(b) = np.dot(a,b)
- np.dot(a,b)とnp.dot(b,a)の解は異なる場合がある
- np.array(python-list)でPythonリストをNumpy配列へ変換
- np.ndarray.tolist()でNumpy配列からPythonリストへ変換

In [63]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [66]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [67]:
# numpy行列の掛け算（行列a * 行列b）
a * b

array([[ 6, 14],
       [24, 36]])

各要素毎の掛け算（アダマール積）になる

In [68]:
# 通常の行列の積
np.dot(a, b)

array([[22, 25],
       [50, 57]])

A x B ≠ B x A  →　解が同一とは限らない

In [69]:
np.dot(b, a)

array([[27, 40],
       [35, 52]])

In [70]:
a.dot(b)

array([[22, 25],
       [50, 57]])

In [71]:
b.dot(a)

array([[27, 40],
       [35, 52]])

In [72]:
# PythonリストからNumpy配列へ変換方法
c = [[1,2],[3,4]]
c

[[1, 2], [3, 4]]

In [73]:
type(c)

list

In [74]:
c = np.array(c)
c

array([[1, 2],
       [3, 4]])

In [75]:
type(c)

numpy.ndarray

In [76]:
d = [[1,2,3,4,5],[2,3]]
d

[[1, 2, 3, 4, 5], [2, 3]]

In [77]:
type(d)

list

In [79]:
d = np.array(d)
d

array([list([1, 2, 3, 4, 5]), list([2, 3])], dtype=object)

In [80]:
type(d)

numpy.ndarray

In [82]:
# Numpy配列からリストに変換
c = c.tolist()
c

[[1, 2], [3, 4]]

In [83]:
type(c)

list

## 7. 乱数生成

チャプター7「乱数生成」では、Numpyを様々な種類の乱数生成を行います。また基本的な乱数の種類を説明します。分布や基本的な統計用語に不安がある方は、統計 入門 前編の講座も是非受講ください。

- 乱数とはランダムな数値のこと
- 値や分布に応じて種類が分かれている
- 一様乱数は0〜1の一様分布の乱数
- 標準正規分布は標準偏差を1、平均値が0の分布の乱数
- np.random.rand() 一様乱数の生成
- np.random.randn() 標準正規分布の乱数生成
- np.random.randint() 整数の乱数生成
- np.random.seed() 乱数の種（シード）の指定

In [3]:
# 一様乱数　（0 - 1 の一様分布）
np.random.rand(10)

array([0.64429942, 0.08410252, 0.44132879, 0.9965415 , 0.38564625,
       0.78607999, 0.66841587, 0.34154764, 0.30820283, 0.76351899])

In [4]:
np.random.rand(10, 10)

array([[0.68596931, 0.7329969 , 0.34187383, 0.62919599, 0.18701337,
        0.28053138, 0.42958595, 0.15361446, 0.83551952, 0.73346555],
       [0.70217503, 0.59122422, 0.19405769, 0.53352816, 0.63163549,
        0.35772648, 0.44990012, 0.84809652, 0.16822018, 0.20827498],
       [0.04957431, 0.93979935, 0.69779295, 0.35574373, 0.78083765,
        0.80000915, 0.49188873, 0.94338823, 0.37007049, 0.98743581],
       [0.24057157, 0.22767824, 0.06132668, 0.86331089, 0.11389848,
        0.93891793, 0.24190703, 0.49923403, 0.29573072, 0.96923687],
       [0.86792911, 0.02542416, 0.43191579, 0.0299004 , 0.42334695,
        0.10055232, 0.3645184 , 0.20666588, 0.59122563, 0.83036306],
       [0.2629109 , 0.12490734, 0.39961616, 0.41488037, 0.31148159,
        0.54200951, 0.87629852, 0.61116409, 0.84112978, 0.56510964],
       [0.62548336, 0.2082473 , 0.13101559, 0.48733085, 0.69277673,
        0.55748893, 0.53848885, 0.69247538, 0.41603632, 0.07231138],
       [0.38683013, 0.44412988, 0.2636783

In [5]:
# 標準正規分布（Standard Normal Distribution） 
# 平均値 = 0 & 標準偏差 = 1
# 平均値（Mean)　/　中央値（Median）
np.random.rand(1)

array([0.00118311])

In [17]:
randn5000 = np.random.rand(5000, 5000)
randn5000

array([[0.53646749, 0.07247673, 0.29478375, ..., 0.03026731, 0.14167959,
        0.20154307],
       [0.45999956, 0.67430069, 0.54125576, ..., 0.44881399, 0.61067608,
        0.27569965],
       [0.59099534, 0.79278391, 0.03250473, ..., 0.14785069, 0.28648595,
        0.55266365],
       ...,
       [0.77118998, 0.16422199, 0.32952605, ..., 0.03422843, 0.99281963,
        0.45203582],
       [0.7104178 , 0.54111323, 0.81364574, ..., 0.61618342, 0.4904523 ,
        0.38321151],
       [0.64430953, 0.42188679, 0.46482228, ..., 0.30527422, 0.24844327,
        0.06296547]])

In [18]:
randn5000.shape

(5000, 5000)

In [19]:
randn5000.mean()

0.49997501551830226

In [20]:
randn5000.std()

0.2887417348263192

In [21]:
# 整数乱数の生成
np.random.randint(100)

69

In [23]:
# 1 〜 30 までの5０故の乱数を生成
np.random.randint(1,30,10)

array([ 7, 15, 16, 22,  3, 29, 26, 27,  9,  3])

In [26]:
# 10行 x 10列の３０までの乱数を生成
randint30 = np.random.randint(1, 30,(10,10))
randint30

array([[17, 28,  6, 23, 20, 11, 28, 26, 13,  4],
       [29, 17,  4, 11, 27, 13, 22, 12, 13, 27],
       [ 4, 15, 21,  1, 11,  9, 13, 10,  6,  5],
       [11, 21, 24, 14, 22,  2,  2,  2,  9, 26],
       [26, 13, 15, 29, 20, 20, 20,  2, 10, 13],
       [ 9, 14,  9, 14, 20, 17, 15,  5, 25,  9],
       [25, 14, 17, 16, 13,  7, 11, 27,  4,  8],
       [27, 19, 12, 25, 29,  8, 22,  9, 24, 15],
       [22,  5,  3, 14, 16,  8, 24, 29,  3, 22],
       [25, 20,  4, 29, 25, 17, 24, 13, 13,  6]])

In [27]:
randint30.shape

(10, 10)

In [29]:
# 乱数発生の初期化
# seed を固定すると、毎回同じ乱数生成が可能
np.random.seed(100)

In [30]:
np.random.randn()

-1.7497654730546974

In [31]:
np.random.randn()

0.34268040332750216

In [32]:
np.random.randn()

1.153035802563644

In [37]:
# 乱数の種（シード）の指定
np.random.seed(100)

In [38]:
np.random.randn()

-1.7497654730546974

In [40]:
np.random.randn()

1.153035802563644

## 8. 行列の演算と処理

チャプター8「行列の演算と処理」では、Numpyを使って逆行列や転置行列など、行列の処理・演算を行いましょう。行列の積の求め方や線形代数の基礎に不安がある方は、線形代数 入門の講座も是非受講ください。

- np.linalg.inv(ndarray) ndarrayの逆行列を算出
- ndarray.T ndarrayの転置行列を算出
- np.diag(ndarray) ndarrayの対角成分の取得
- np.inner() ベクトルの内積を算出
- np.outer() ベクトルの外積を算出

#### 逆行列
何かをかけたら、単位行列になる行列

In [41]:
a = np.array([[2,5],[1,3]])
a

array([[2, 5],
       [1, 3]])

In [43]:
# np.linalg.inv() : 逆行列の計算
b = np.linalg.inv(a)
b

array([[ 3., -5.],
       [-1.,  2.]])

In [46]:
# np.dot : 行列の積で、単位行列になることを確認
np.dot(a, b)

array([[1., 0.],
       [0., 1.]])

In [47]:
# 転置行列(Transposed Matrix)
# a.T : a transposed = 行列aの転置行列
c = np.array([[3,1],[2,6],[4,5]])
c

array([[3, 1],
       [2, 6],
       [4, 5]])

In [48]:
c.T

array([[3, 2, 4],
       [1, 6, 5]])

In [49]:
a

array([[2, 5],
       [1, 3]])

In [50]:
a.T

array([[2, 1],
       [5, 3]])

In [51]:
type(a)

numpy.ndarray

In [52]:
# 対角成分の取得
d = np.array([[1,0,0],[0,1,0],[0,0,1]])
d

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [54]:
# 対角の成分だけ取り出したい（１だけ）
# diagonal = 対角の
np.diag(d)

array([1, 1, 1])

In [55]:
# ベクトルの外積と内積
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [57]:
b = np.array([5,6,7,8])
b

array([5, 6, 7, 8])

In [58]:
# 内積を求める
np.inner(a, b)

70

In [60]:
#　外積を求める
np.outer(a, b)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

## 9. 数学系の関数

チャプター9「数学系の関数」では、Numpyを使って三角関数や指数/対数関数など、機械学習で出てくる数学系の関数を学びましょう。

- np.sin() sineを算出（度数ではなくラジアン）
- np.cos() cosineを算出（度数ではなくラジアン）
- np.tan() tangentを算出（度数ではなくラジアン）
- np.radians() 度数からラジアンへ変換
- np.exp() 指数関数（Exponential / エクスポネンシャル）
- np.log() 対数関数（Logarithm / ロガリズム）
- np.sign() 「正」「負」「ゼロ」を分別
- np.rint() 小数点を四捨五入して整数にする
- np.modf() 小数点部と整数部に分けて配列で返す

#### 三角関数（sin, cos, tan）

In [8]:
# tan45°　= 1     ※ラジアンを指定する（degreeではない）
np.tan(45)

1.6197751905438615

1にならない

In [9]:
# 度数からラジアンに変換
rd = np.radians(45)
rd

0.7853981633974483

In [10]:
#ラジアンで指定する
np.tan(rd)

0.9999999999999999

ほぼ１になる

In [12]:
#　sin90° = 1
rd = np.radians(90)
rd

1.5707963267948966

In [13]:
np.sin(rd)

1.0

#### 指数関数と対数関数

In [15]:
# 指数関数（Exponential Function）
# 各要素に自然対数の底「e:2.718281...」を返す
# np.e = 自然対数の底「e」
np.e

2.718281828459045

In [18]:
# 指数関数を計算
np.exp(2)  # eの２乗

7.38905609893065

e = 2.7182... の２乗　→　7.389...

In [20]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [21]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [24]:
# 対数関数 (Logarithmic) を計算
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [25]:
b = np.array([-5, -1, -1, 0, 10, 15, -1, 2])
b

array([-5, -1, -1,  0, 10, 15, -1,  2])

In [26]:
# 正と負とゼロで分けたい場合に使う
np.sign(b)

array([-1, -1, -1,  0,  1,  1, -1,  1])

各要素で正＝１、負＝-1、0=0を返す

In [29]:
#　小数点を扱う関数
c = np.random.randn(10)  #標準正規分布に属する乱数生成
c

array([ 0.79428785, -0.18546345, -0.18932315,  0.9294602 ,  1.36619725,
       -0.50761497,  0.47521222, -0.3911782 ,  0.35200667,  0.72710939])

In [30]:
# 小数点以下を四捨五入で切り捨て、切り上げをして整数にする
np.rint(c)

array([ 1., -0., -0.,  1.,  1., -1.,  0., -0.,  0.,  1.])

In [32]:
# 要素ごとに整数部分と小数部分に分けて配列に戻す
np.modf(c)

(array([ 0.79428785, -0.18546345, -0.18932315,  0.9294602 ,  0.36619725,
        -0.50761497,  0.47521222, -0.3911782 ,  0.35200667,  0.72710939]),
 array([ 0., -0., -0.,  0.,  1., -0.,  0., -0.,  0.,  0.]))

## Numpy 理解度確認テスト

【質問1】numpy 配列
下記において、a[1,2]の実行の結果で求められる数値で正しいものは選んで下さい。

import numpy as np
a = np.array([[2,5,10],[3,6,8],[10,23,1]])
a[1,2]

- 5
- 3
- 8
- 2

【質問2】numpy 配列
下記において、b[:,2]の実行の結果で求められる数値で正しいものは選んで下さい。

import numpy as np
b = np.array([[2,7,10,2],[3,43,1,9]])
b[:,2]

- array([10,1])
- array([1,9])
- array([2,7])
- array([3,43])

【質問3】numpy 配列の演算
下記において、a + bの実行の結果で求められる正しいもの以下から選んで下さい。

import numpy as np
b = np.array([[2,5],[6,1]])
a = np.array([[1,3],[2,4]])

a + b

選択肢 A
array([[3, 7],
       [8, 6]])

選択肢 B
array([[3, 8],
       [8, 5]])

- A
- B

【質問4】numpy 配列の演算
下記において、a * bの実行の結果で求められる正しいもの以下から選んで下さい。 
import numpy as np
a = np.array([[2,3],[6,2]])
b = np.array([[1,4],[5,2]])
a * b

選択肢 A
array([[ 12, 6],
       [ 5,  8]])

選択肢 B
array([[ 2, 12],
       [30,  4]])

選択肢 C
array([[ 6, 12],
       [ 4,  8]])

- A
- B
- C

【質問5】行列の積
下記において、np.dot(a, b)の実行の結果で求められる正しいもの以下から選んで下さい。

Pythonを使わず手動で計算をして下さい。


a = np.array([[2,3],[6,2]])
b = np.array([[1,4],[5,2]])
np.dot(a, b)

選択肢 A

array([[12,  6],
       [ 5,  8]])
選択肢 B

array([[ 2, 12],
       [30,  4]])
選択肢 C

array([[17, 14],
       [16, 28]])
       
- A
- B
- C

【質問6】逆行列
下記において、np.dot(a, b)の実行の結果で正しいものを選んで下さい。

a = np.array([[2,1],[1,2]])
b = np.linalg.inv(a)
np.dot(a, b)
選択肢 A

array([[ 0.6, -0.3],
       [-0.3,  0.6]])
選択肢 B

array([[ 1.,  0.],
       [ 0.,  1.]])
選択肢 C

array([[ 0.,  1.],
       [ 1.,  0.]])
       
- A
- B
- C